<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/CustomField
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-order-attributes
 */
?>
<?php $order = $block->getOrder(); ?>
<?php if ($order) : ?>
<section class="admin__page-section order-additional-information">
    <div class="admin__page-section-title">
        <strong class="title"><?php echo /* @escapeNotVerified */ __('Additional Information'); ?></strong>
    </div>
    <div id="<?php echo $block->getHtmlId() ?>"
         class="admin__page-section-content order-additional-information-container">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tr>
                        <th>Delivery Note</th>
                        <td><?php echo $order->getDeliveryNote(); ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>